name: Run Standard Pipeline

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
    branches:
      - 'main'
      - 'feat/**'
      - 'feature-1'
      - 'feature-2'
      - 'feature-3'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'develop'
jobs:
  build:
    uses: tpearson84/Reusable-Workflows/.github/workflows/ci-main-workflow.yml@main
