name: Run Standard Pipeline

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
    branches:
      - 'main'
      - 'feat/**'
      - 'feature-1'
      - 'feature-2'
      - 'feature-3'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main    
  workflow_dispatch:
  
jobs:
  build:
    uses: nsf-1950/Reusable-Workflows/.github/workflows/ci-main-maven-workflow.yml@main
