name: Publish Helm Chart

on:
  workflow_dispatch:
  # Run Stable Chart
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  # Run RC Chart
  push:
    branches:
      - main
   # Uncomment when using new workflow   
#  pull_request_review:
#    types: [submitted]
#    branches:
#      - main


permissions:
  contents: write
  packages: write
  
jobs:
#!======================================= RC =======================================!#
  helm-main-workflow:
    uses: tpearson84/Reusable-Workflows/.github/workflows/helm-main-workflow.yml@main
